---
custom: ${file(config.${self:provider.stage}.yml)}

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.profile}

service: ${self:custom.appName}

resources:
  Resources:
    AppS3Bucket: ${file(resources/app_bucket.yml)}
    AppS3BucketPolicy: ${file(resources/app_bucket_policy.yml)}
    StaticSiteCert: ${file(resources/ssl_certificate.yml)}
    CloudFrontDistribution: ${file(resources/cf_distro.yml)}
    DnsRecord: ${file(resources/dns_record.yml)}
    DnsRecord2: ${file(resources/dns_record.2.yml)}

plugins:
  - serverless-single-page-app-plugin